{
 "title": "KubernetesDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage Master Component",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum((container_memory_usage_bytes{ namespace=\"kube-system\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores Under Utilised ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[30m]) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\"})) * -1 >0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. Nodes Flaping (Ready/Not Ready)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(changes(kube_node_status_condition{status=\"true\",condition=\"Ready\"}[15m])) by (node) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pod Restart Across Namespace",
   "type": "timeseries",
   "description": "With this query, you’ll get all the pods that have been restarting. This is really important since a high pod restart rate usually means CrashLoopBackOff.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace)(changes(kube_pod_status_ready{condition=\"true\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Nodes Ready In The Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pods Running based on Namespace",
   "type": "timeseries",
   "description": "This Dashboard describes the Master Node Component up or not",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count by(namespace) (kube_pod_info{endpoint=\"http\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. Of Pods Not Running Across Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_status_ready{condition=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}